# -*- coding: utf-8 -*-
"""Deeper race/origin stamps: extra origin events, new flags, and later reads."""
from __future__ import annotations


def _d0(*eids: int) -> list[dict]:
    return [{"eventId": i, "delay": 0} for i in eids]


def apply_heritage(add) -> None:
    _origin_set_events(add)
    _birth_forks(add)
    _flag_echoes(add)


def _origin_set_events(add) -> None:
    childhood = [
        (1320, "priest", "confession_seal",
         "你出身牧师家庭。告解的人把一句不该说的话留给空气。你把它当成没听见的石头。",
         {"wis": 1}),
        (1321, "soldier", "camp_discipline",
         "你出身军人家庭。木剑被允许真正出鞘一次。刃口很钝，规矩很锋利。",
         {"str": 1, "con": 1}, {"has_sword": True}),
        (1322, "mage", "spellbook_stain",
         "你出身法师家庭。你把一页被墨浸透的禁咒抄错了位置，爆炸少发生一次。",
         {"int": 1, "wis": 1}),
        (1323, "merchant", "caravan_pass",
         "你出身商人家庭。车队给你一张旧路条。关卡多看了一眼姓氏，少收了一截税。",
         {"int": 1, "gold": 3}),
        (1324, "farmer", "barn_key",
         "你出身农人家庭。仓门的钥匙交到你手上。比交剑更早，也更沉。",
         {"wis": 1, "con": 1}),
        (1325, "artisan", "workshop_claim",
         "你出身工匠家庭。工位上有人抢尺子。你把尺放回原位，尺比拳头有用。",
         {"int": 1, "con": 1}),
        (1326, "street", "fence_contact",
         "你出身街头。有人教你哪扇后门收脏货。你把干净的那件留下，把地址记住。",
         {"agi": 1, "gold": 1, "wis": 1}),
        (1327, "noble", "estate_claim",
         "你出身贵族家庭。文书上第一次出现你的教名。门为它开了一条缝，金库没有。",
         {"cha": 1, "int": 1, "gold": 4}),
        (1328, "tribe", "spirit_name",
         "你出身氏族部落。老人把族名贴在你耳边。风停了一息，像在对名单。",
         {"wis": 1, "cha": 1}),
        (1329, "temple_order", "chapel_watch",
         "你在骑士团院落里长大。圣堂夜班第一次排到你。蜡烛比剑先醒。",
         {"wis": 1, "con": 1}),
    ]
    for eid, origin, flag, desc, fx, *rest in childhood:
        extra = rest[0] if rest else {}
        flags = {flag: True}
        flags.update(extra)
        add({
            "eventId": eid, "desc": desc,
            "minAge": 7, "maxAge": 16, "maxTriggers": 1, "baseWeight": 11,
            "requiredFlags": [{"origin": origin}],
            "effects": fx, "flags": flags,
            "cooldownGroups": ["childhood", "heritage_set"],
            "cooldownMinInterval": 2,
        })

    youth = [
        (1340, "priest", "relic_keeper",
         "你出身牧师家庭。一枚没人愿碰的圣物交给你保管。尘比光多，你仍擦。",
         {"wis": 1, "con": 1}),
        (1341, "soldier", "line_officer",
         "你出身军人家庭。临时编制把你写成伍长。你把逃兵写成还在，把锅写成热的。",
         {"str": 1, "cha": 1, "con": 1}),
        (1342, "mage", "tower_key",
         "你出身法师家庭。老师的旧钥匙还适配塔门。书比人老实，楼梯比记忆陡。",
         {"int": 1, "wis": 1}),
        (1343, "merchant", "trade_credit",
         "你出身商人家庭。你的名字第一次能当押金。你没用满，掌柜却记满了。",
         {"cha": 1, "int": 1, "gold": 5}),
        (1344, "farmer", "harvest_hands",
         "你出身农人家庭。一村的麦要在雨前收完。你的手裂了，仓满了。",
         {"con": 1, "str": 1, "cha": 1}),
        (1345, "artisan", "guild_apprentice",
         "你出身工匠家庭。行会在你的记号下盖了印。工钱按匠人算，汗仍按学徒流。",
         {"int": 1, "gold": 3, "con": 1}),
        (1346, "street", "alley_debt",
         "你出身街头。有人来讨旧人情。你给面包，不给名单。",
         {"wis": 1, "gold": -1, "cha": 1}),
        (1347, "noble", "retainer_name",
         "你出身贵族家庭。旧家臣仍用那个称呼喊你。你请他喝酒，没请他复职。",
         {"cha": 1, "wis": 1}),
        (1348, "tribe", "hunt_totem",
         "你出身氏族部落。你把猎图腾转对方向。今夜的兽绕开帐篷，火更亮。",
         {"wis": 1, "str": 1}),
        (1349, "temple_order", "oath_scar",
         "你在骑士团院落里长大。旧誓在掌纹里留下一道白印。需要信的人会看手。",
         {"cha": 1, "wis": 1, "str": 1}),
    ]
    for eid, origin, flag, desc, fx in youth:
        add({
            "eventId": eid, "desc": desc,
            "minAge": 16, "maxAge": 32, "maxTriggers": 1, "baseWeight": 10,
            "requiredFlags": [{"origin": origin}],
            "effects": fx, "flags": {flag: True},
            "cooldownGroups": ["heritage_set", f"origin_{origin}"],
            "cooldownMinInterval": 3,
        })

    extra = [
        (1360, "priest", "liturgy",
         "你出身牧师家庭。走调的葬礼被你用一句旧祷词扶正。死者不说话，活人松了口气。",
         {"wis": 1, "cha": 1}),
        (1361, "soldier", "drill",
         "你出身军人家庭。民兵把阵形走散。你把口令喊回去，他们把命走回来。",
         {"str": 1, "cha": 1}),
        (1362, "mage", "arcane_tutelage",
         "你出身法师家庭。学徒的法阵少一条线。你闭着眼补上，爆炸改去隔壁。",
         {"int": 1}),
        (1363, "merchant", "ledger",
         "你出身商人家庭。账本里有一页比别的页新。你把它抽出来，价钱突然诚实了。",
         {"int": 1, "gold": 2}),
        (1364, "farmer", "soil_sense",
         "你出身农人家庭。你踩一脚就知道这垄该休耕。村长不信，秋收信了。",
         {"wis": 1, "con": 1}),
        (1365, "artisan", "craft_eye",
         "你出身工匠家庭。梁上的裂比敌人的刀先被你看见。钉子比誓言快。",
         {"int": 1, "str": 1}),
        (1366, "street", "streetwise",
         "你出身街头。卫兵去搜巷口，你已经把孩子从另一头带出来。",
         {"agi": 1, "wis": 1}),
        (1367, "noble", "heraldry",
         "你出身贵族家庭。宴会上你从袖扣认出旧同盟。对方以为纹章只是装饰。",
         {"cha": 1, "int": 1}),
        (1368, "tribe", "ancestral_fire",
         "你出身氏族部落。风向转了。你让营地离开干河床。夜里河床重新变成河。",
         {"wis": 1, "con": 1}),
        (1369, "temple_order", "oath_child",
         "你在骑士团院落里长大。有人要你见证一句永远。你让他们改成今晚。今晚有效。",
         {"wis": 1, "cha": 1}),
    ]
    for eid, origin, flag, desc, fx in extra:
        add({
            "eventId": eid, "desc": desc,
            "minAge": 14, "maxAge": 55, "baseWeight": 7, "maxTriggers": 3,
            "requiredFlags": [{"origin": origin, flag: True}],
            "effects": fx,
            "cooldownGroups": ["heritage", f"origin_{origin}"],
            "cooldownMinInterval": 5,
        })


def _fork(add, eid: int, scene: str, flag: str, yes: str, yes_fx: dict, no: str, no_fx: dict,
          *, lo: int = 16, hi: int = 75, w: int = 6) -> None:
    add({
        "eventId": eid, "desc": scene,
        "minAge": lo, "maxAge": hi, "maxTriggers": 2, "baseWeight": w,
        "cooldownGroups": ["flag_fork", "heritage"],
        "cooldownMinInterval": 8,
        "followUp": _d0(eid + 1, eid + 2),
    })
    add({
        "eventId": eid + 1, "desc": yes,
        "minAge": lo, "maxAge": hi, "naturalUnlock": False, "baseWeight": 12,
        "requiredFlags": [{flag: True}],
        "effects": yes_fx,
    })
    add({
        "eventId": eid + 2, "desc": no,
        "minAge": lo, "maxAge": hi, "naturalUnlock": False, "baseWeight": 10,
        "requiredFlags": [{flag: False}],
        "effects": no_fx,
    })


def _birth_forks(add) -> None:
    rows = [
        (7030, "有人要你立刻顶一个空缺的行当：记账、守夜、或把话说圆。",
         "versatile",
         "你把别人的行当学了一半。一半已经够把今晚撑过去。", {"int": 1, "cha": 1},
         "你不会。你把位置让给会的人，自己去搬箱子。", {"str": 1, "con": 1}),
        (7033, "夜里营外有一声不该出现的动静。有人说是风。",
         "keen_senses",
         "你听见的不是风。是屏息。你把火拨暗，把弓拉满。", {"agi": 1, "wis": 1},
         "你也当它是风。风有时只是风，有时会咬人一口。", {"con": 1}),
        (7036, "坏酒过桌。有人已经开始夸它的年份。",
         "stout",
         "酒劲对你像水。你把夸年份的人扶到门外吹风。", {"con": 2},
         "你喝了一口，世界斜了。你坐到天亮才把桌沿认回来。", {"con": -1, "wis": 1}),
        (7039, "石头从屋檐落下。下面是你刚才站的位置。",
         "lucky",
         "你早一步侧身。石头在你鞋边鞠躬。你捡起它，当成运气的收据。", {"agi": 1, "gold": 1},
         "石头擦过肩膀。淤青很诚实，运气今天放假。", {"con": -1, "str": 1}),
        (7042, "一具咬死的机关挡住去路。说明书上画着不该这样的齿轮。",
         "tinkerer",
         "你用发钗和三句脏话让它重新讲理。路通了，说明书作废。", {"int": 2},
         "你砸。砸开了，也砸响了不该响的铃。", {"str": 1, "agi": 1}),
        (7045, "有人先动手，为了证明自己不怕你这种脸。",
         "savage",
         "你结束得比证明更快。对方躺着完成了自己的课题。", {"str": 2, "cha": -1},
         "你讲理。讲理需要时间。时间里你挨了一拳，也学会了下一句。", {"cha": 1, "con": -1}),
        (7048, "两张桌子同时向你招手：人类的短歌，精灵的长调。",
         "two_worlds",
         "你各坐半席，把酒钱付成一份。两边都觉得你偏心，又都留了位置。", {"cha": 1, "wis": 1},
         "你选了一边。另一边的杯子空着，像一句没说完的介绍。", {"cha": 1}),
        (7051, "火把不够。有人问谁能把夜路照亮一段。",
         "dragon_breath",
         "你警告过他们后退。帐幔没有听见，草叶听见了。路亮了一息。", {"str": 1, "cha": 1},
         "你把火把掰成两截。两截都不够亮，人还是往前走。", {"wis": 1}),
        (7054, "凡火从炉子里跳出来，扑向最近的袍摆。",
         "infernal",
         "火碰到你像碰到湿木头。你把它踩灭，鞋底多了一点硫磺味。", {"con": 1, "int": 1},
         "火咬了你一口。你打滚，旁人泼水，夜还长。", {"con": -1, "agi": 1}),
        (7057, "神殿门口洒圣水。执事的手在你面前停了一停。",
         "stigma",
         "多洒的那一滴落在你角边。你擦掉。门仍开着，只是窄了一指。", {"wis": 1, "cha": 1},
         "水均匀地洒过每个人。你像任何人一样湿了一点点。", {"cha": 1}),
        (7060, "矿道粉尘灌进来。有人开始咳成另一种颜色。",
         "stone_blood",
         "你咳两声就忘。肺像认识这些石头。", {"con": 2},
         "你咳到看见星星。星星在地下，这不合理，你仍看见。", {"con": -1, "wis": 1}),
        (7063, "箭从队列顶上压下来。高个子先成为靶子。",
         "small_stature",
         "箭从你头顶飞过，像专为别人准备。你从膝边把路摸清楚。", {"agi": 2},
         "你也得低头。低头的人活下来，腰很痛。", {"con": 1, "agi": 1}),
        (7066, "有人按人类的年份给你做寿，蜡烛插得像笑话。",
         "long_lived",
         "你吹灭蜡烛，没有纠正他们。朋友的坟上会长苔，你还在学新歌。", {"wis": 2, "con": 1},
         "你把寿面吃完。年份对你刚好，笑话对你也刚好。", {"cha": 1, "con": 1}),
        (7069, "走调的仪式卡在半句祷词上。死者等着，活人不会。",
         "liturgy",
         "祷词在你嘴里有形状。你把走调的部分扶正，香火重新听话。", {"wis": 2, "cha": 1},
         "你跟着哼。哼到走调更响。有人求你停下，你改去搬凳。", {"con": 1}),
        (7072, "溃兵乱跑。旗帜还在，人已经不像一行。",
         "drill",
         "你把口令喊回去。他们把步子走回来，像记起自己的脚。", {"str": 1, "cha": 1, "con": 1},
         "你跟着跑。跑也是一种活。活到下一个路口再谈阵形。", {"agi": 1, "con": 1}),
        (7075, "学徒的法阵少一条线。空气开始发甜，这不是好甜。",
         "arcane_tutelage",
         "你闭着眼补上那条线。甜味散了，学徒的眉毛还在。", {"int": 2},
         "你去提水。水有用，水比符文好懂。", {"wis": 1, "con": 1}),
        (7078, "账本合上时比打开时厚了一页。掌柜说是纸的问题。",
         "ledger",
         "你抽出那页。价钱突然诚实，掌柜的笑薄了一层。", {"int": 1, "gold": 3},
         "你付钱。纸的问题有时要用铜解决。", {"gold": -1, "wis": 1}),
        (7081, "田里生了陌生斑。有人要浇圣水，有人要再播一层。",
         "soil_sense",
         "你让他们把病株烧掉、换垄。今年少饿一旬。", {"wis": 1, "con": 1, "cha": 1},
         "你跟着浇。浇完仍斑。斑不管意见。", {"con": 1}),
        (7084, "城门铰链咬死。车队堵成一条发愁的蛇。",
         "craft_eye",
         "你看见裂在哪一颗钉上。天亮后门会鞠躬。", {"int": 1, "str": 1, "gold": 2},
         "你去推。推到肩膀青了，门仍有自己的脾气。", {"str": 1, "con": -1}),
        (7087, "一只手伸向旁边人的口袋。卫兵在看天。",
         "streetwise",
         "你比卫兵更早看见那只手。手收回去，下巴抬起来。", {"agi": 1, "wis": 1},
         "你喊抓贼。贼跑了，卫兵开始盘问你。", {"cha": 1, "con": 1}),
        (7090, "有人按你的旧姓要一份礼，语气像在收税。",
         "heraldry",
         "你从袖扣认出他并不属于那份税。礼貌送出，钱留下。", {"cha": 1, "int": 1},
         "你送了一点钱把人送走。礼貌有时比纹章贵。", {"gold": -2, "cha": 1}),
        (7093, "干河床看起来像一条好路。马已经想下去。",
         "ancestral_fire",
         "你让营地挪开。夜里河床重新变成河，马重新变成马。", {"wis": 1, "con": 1},
         "你们抄近路。水来时你们改抄逃路。", {"agi": 1, "con": -1}),
        (7096, "有人要你见证一句‘永远’，墨已经舔在笔尖上。",
         "oath_child",
         "你让他们把永远改成今晚。今晚有效，明天再写明天。", {"wis": 1, "cha": 1},
         "你按了手印。永远很轻，纸却会黄。", {"cha": 1}),
    ]
    for row in rows:
        _fork(add, *row)


def _flag_echoes(add) -> None:
    echoes = [
        (7100, "versatile", 16, 80,
         "路需要一个会一点什么的人。你把‘一点’拿出来用，用完再学下一点。",
         {"int": 1, "wis": 1}),
        (7101, "keen_senses", 12, 85,
         "林子里有人屏息。你先听见，把同伴的袖口往回拉。",
         {"agi": 1, "wis": 1}),
        (7102, "long_lived", 32, 110,
         "你看着人类朋友的孩子长到能喝酒。酒还是那种酒，人已经换代。",
         {"wis": 1, "con": 1}),
        (7103, "stout", 16, 90,
         "酒劲对别人像锤子，对你像水。你把醉倒的人逐个扶出门。",
         {"con": 1, "cha": 1}),
        (7104, "stone_blood", 16, 90,
         "矿尘进肺，你咳两声就忘。石头认你，像认一个迟到的亲戚。",
         {"con": 1}),
        (7105, "lucky", 10, 80,
         "赌局的骰子朝你微笑。你收了微笑，没把整张桌子收走。",
         {"gold": 2, "agi": 1}),
        (7106, "small_stature", 12, 75,
         "栅栏的缝只对你是门。你从缝里把钥匙取回来，门仍对别人关着。",
         {"agi": 1, "gold": 1}),
        (7107, "tinkerer", 14, 85,
         "锁咬死了。你让它重新讲理。讲理费一根发钗，省一扇被砸的门。",
         {"int": 1, "gold": 1}),
        (7108, "savage", 16, 70,
         "谈判开始前对方先看你的牙。你把牙收起来，把合同打开。",
         {"str": 1, "cha": 1}),
        (7109, "two_worlds", 16, 90,
         "两边的暗语你都能接上。信比你更受欢迎，你不介意当信。",
         {"cha": 1, "wis": 1}),
        (7110, "dragon_breath", 16, 80,
         "湿柴不着。你把鼻息压得很低，火仍肯起来。菜单卷了边。",
         {"str": 1, "con": 1}),
        (7111, "infernal", 16, 85,
         "普通的火碰到你像碰到湿木头。铁匠请你靠近炉子，又请你别靠太近。",
         {"con": 1, "int": 1}),
        (7112, "stigma", 12, 80,
         "神殿正门对你关着。侧门的香火没问角的形状。你把钱放在侧门。",
         {"wis": 1, "gold": -1, "cha": 1}),
        (7113, "liturgy", 12, 80,
         "祷词在别人嘴里是声音，在你嘴里有形状。你把走调的仪式扶正。",
         {"wis": 1, "cha": 1}),
        (7114, "drill", 16, 70,
         "民兵要你示范步法。你把他们走成一行，而不是一群鹅。",
         {"str": 1, "cha": 1}),
        (7115, "arcane_tutelage", 14, 70,
         "法阵少一条线。你闭着眼补上。学徒以为你在睡觉，你以为他在爆炸。",
         {"int": 1, "wis": 1}),
        (7116, "ledger", 16, 75,
         "你看出账本里的假页。假页被抽走，真账突然变薄。",
         {"int": 1, "gold": 2}),
        (7117, "soil_sense", 16, 80,
         "你踩一脚就知道这地该休耕。休耕的那年邻居骂你，第二年请你喝酒。",
         {"wis": 1, "con": 1}),
        (7118, "craft_eye", 16, 80,
         "梁上的裂比刀先被你看见。钉子比誓言快，屋顶比预言久。",
         {"int": 1, "str": 1}),
        (7119, "streetwise", 12, 75,
         "你比卫兵更早看见伸进口袋的手。卫兵看见的是你抬起的下巴。",
         {"agi": 1, "wis": 1}),
        (7120, "heraldry", 16, 80,
         "你从袖扣认出旧同盟。对方以为你忘了。你把忘字留给他。",
         {"cha": 1, "int": 1}),
        (7121, "ancestral_fire", 16, 80,
         "风向转了。你让营地离开干河床。夜里河床重新变成河。",
         {"wis": 1, "con": 1}),
        (7122, "oath_child", 16, 75,
         "有人要你见证誓言。你让他们把永远改成今晚。今晚有效。",
         {"wis": 1, "cha": 1}),
        (7123, "choir_voice", 10, 70,
         "你起了个头，走调的队列被你拽回来。香火像听懂了拍子。",
         {"cha": 1, "wis": 1}),
        (7124, "watch_habit", 14, 70,
         "换岗的人困了。你先看见林线的影子，把铃握在手里不摇。",
         {"wis": 1, "con": 1}),
        (7125, "cantrip_spark", 12, 70,
         "蜡烛灭了。你的指尖比火折子快。屋里重新有脸。",
         {"int": 1}),
        (7126, "credit_name", 16, 75,
         "掌柜听你报出身，账期宽了三天。三天够把货变成更好的谎。",
         {"gold": 2, "cha": 1}),
        (7127, "weather_eye", 14, 80,
         "你让他们提前收麦。冰雹只砸到空垄。空垄也会谢人。",
         {"wis": 1, "cha": 1}),
        (7128, "maker_mark", 16, 80,
         "你从一枚钉子认出师傅的手。赝品退回去，真货留下茧。",
         {"int": 1, "gold": 1}),
        (7129, "rooftop_path", 14, 65,
         "巷战在地面。你在瓦上。瓦比石板记得你的脚步。",
         {"agi": 1, "wis": 1}),
        (7130, "court_manners", 16, 80,
         "你用错了叉子，却用对了头衔。叉子被原谅，头衔被记住。",
         {"cha": 1, "int": 1}),
        (7131, "wild_track", 14, 80,
         "脚印被雨洗过。你仍读出重量。重量往东，你们不往西。",
         {"wis": 1, "agi": 1}),
        (7132, "squire_token", 14, 70,
         "你把甲片让给新来的孩子，像有人曾经让给你。甲片比誓词亮。",
         {"wis": 1, "cha": 1}),
        (7133, "confession_seal", 16, 80,
         "有人把秘密塞给你。你把它当成没听见的石头。石头不长嘴。",
         {"wis": 1, "cha": 1}),
        (7134, "camp_discipline", 16, 70,
         "营地要散。你把锅碗和岗哨重新排好。散变成轮班。",
         {"con": 1, "str": 1}),
        (7135, "spellbook_stain", 16, 70,
         "你闻出墨里的错配方。爆炸改去别人的眉毛，你的书多了一块纪念。",
         {"int": 1, "wis": 1}),
        (7136, "caravan_pass", 16, 70,
         "关卡认这张旧路条。税少了一截，路多了一截。",
         {"gold": 2, "int": 1}),
        (7137, "barn_key", 16, 80,
         "饥年有人按钥匙的记忆找你。你打开仓。钥匙比剑先到。",
         {"cha": 1, "gold": -2, "wis": 1}),
        (7138, "workshop_claim", 16, 75,
         "有人抢工位。你把尺放在桌上。尺比拳头有用，工比吵有用。",
         {"int": 1, "con": 1}),
        (7139, "fence_contact", 16, 70,
         "脏货有人收。你把干净的那件留下，把脏的那件变成铜。",
         {"gold": 2, "agi": 1}),
        (7140, "estate_claim", 16, 80,
         "文书上的旧姓替你开了一扇门。门后没有金库，有一条能走的走廊。",
         {"cha": 1, "int": 1}),
        (7141, "spirit_name", 16, 80,
         "你把族名念对。风停了一息。一息够把迷路的人喊回来。",
         {"wis": 1, "cha": 1}),
        (7142, "chapel_watch", 16, 75,
         "圣堂夜盗碰到醒着的你。他们改去别的屋顶，屋顶谢谢你。",
         {"wis": 1, "str": 1}),
        (7143, "relic_keeper", 18, 85,
         "圣物要人守。你守到尘比光多。尘也不许人伸手。",
         {"wis": 1, "con": 1}),
        (7144, "line_officer", 18, 70,
         "临时编制把你写成伍长。你把逃兵写成还在，把锅写成热的。",
         {"str": 1, "cha": 1}),
        (7145, "tower_key", 18, 80,
         "老师的钥匙还适配旧塔。书比人老实，楼梯比记忆陡。",
         {"int": 1, "wis": 1}),
        (7146, "trade_credit", 18, 75,
         "你的名字能当押金。这一次你没用满，下一次别人用了你的满。",
         {"gold": 3, "cha": 1}),
        (7147, "harvest_hands", 18, 80,
         "你帮着收完一村的麦。手裂了，仓满了，名字留在田埂上。",
         {"con": 1, "cha": 1}),
        (7148, "guild_apprentice", 18, 75,
         "行会认你的记号。工钱按匠人算，汗仍按学徒流。",
         {"gold": 2, "int": 1}),
        (7149, "alley_debt", 18, 70,
         "有人来讨旧人情。你给面包，不给名单。面包比名单干净。",
         {"wis": 1, "gold": -1, "cha": 1}),
        (7150, "retainer_name", 18, 80,
         "旧家臣还用那个称呼。你请他喝酒，没请他复职。酒比爵位实在。",
         {"cha": 1, "wis": 1}),
        (7151, "hunt_totem", 18, 80,
         "你把图腾转对方向。今夜的兽绕开帐篷，火把你的影子站直。",
         {"wis": 1, "str": 1}),
        (7152, "oath_scar", 18, 80,
         "旧誓在掌纹里。你把它亮给需要信的人看。信比墨快。",
         {"cha": 1, "wis": 1}),
    ]
    for eid, flag, lo, hi, desc, fx in echoes:
        add({
            "eventId": eid, "desc": desc,
            "minAge": lo, "maxAge": hi, "baseWeight": 6, "maxTriggers": 3,
            "requiredFlags": [{flag: True}],
            "effects": fx,
            "cooldownGroups": [f"hg_{flag}"],
            "cooldownMinInterval": 6,
        })

    false_reads = [
        (7160, "confession_seal",
         "告解的人把秘密说给你听。你没有封口的习惯，秘密自己找到了风。",
         {"cha": 1, "wis": -1}),
        (7161, "camp_discipline",
         "营地要散。没人排岗。锅冷了，人还在吵谁该去打水。",
         {"wis": 1}),
        (7162, "caravan_pass",
         "关卡要路条。你没有。税按最高一档收，路按最慢一档走。",
         {"gold": -2, "con": 1}),
        (7163, "estate_claim",
         "门房问你的姓。你报了，门没有缝。缝是留给文书的。",
         {"cha": 1}),
        (7164, "tower_key",
         "塔门认钥匙，不认脸。你的脸在外面过夜，书在里面睡觉。",
         {"int": 1, "con": -1}),
        (7165, "guild_apprentice",
         "行会看了你的手。手有茧，没有印。工钱按帮工算。",
         {"con": 1, "gold": 1}),
        (7166, "spirit_name",
         "老人问你族名。你把学来的称呼说错一个音。风继续走，人不继续问。",
         {"cha": -1, "wis": 1}),
        (7167, "oath_scar",
         "有人要看你手上的誓印。你摊开掌心，只有茧。茧不能作证。",
         {"wis": 1}),
        (7168, "fence_contact",
         "脏货没人收。你把它埋了。土不问来路，也不给铜。",
         {"wis": 1, "gold": -1}),
        (7169, "barn_key",
         "饥年有人来找仓。仓锁着，钥匙在别人腰上。你只能把干粮掰开。",
         {"cha": 1, "gold": -1}),
        (7170, "choir_voice",
         "唱诗走调。没人把队列拽回来。香火自己害羞地灭了一截。",
         {"con": 1}),
        (7171, "watch_habit",
         "换岗的人困了。林线的影子先到，铃后响。营地多了一夜惊吓。",
         {"con": -1, "agi": 1}),
        (7172, "cantrip_spark",
         "蜡烛灭了。你去找火折子。找着的时候，屋里的脸已经看不见了。",
         {"wis": 1}),
        (7173, "credit_name",
         "掌柜要现钱。你的名字当不了押金。账期是今晚。",
         {"gold": -1, "int": 1}),
        (7174, "weather_eye",
         "冰雹来时麦还在田里。你和别人一样抬头，一样来不及。",
         {"con": -1, "wis": 1}),
        (7175, "maker_mark",
         "钉子是赝品。你到交货才发现。师傅的手不在这枚钉上。",
         {"gold": -1, "int": 1}),
        (7176, "rooftop_path",
         "巷战在地面。你也在地面。石板比瓦更打滑。",
         {"str": 1, "agi": -1}),
        (7177, "court_manners",
         "你用对了叉子，用错了头衔。叉子被原谅，头衔被记到下一季。",
         {"int": 1, "cha": -1}),
        (7178, "wild_track",
         "脚印被雨洗过。你只看见泥。泥往四面，你们猜了一面。",
         {"wis": 1}),
        (7179, "squire_token",
         "新来的孩子要甲片。你没有可让的那一套。你把擦甲布递过去。",
         {"cha": 1}),
        (7180, "spellbook_stain",
         "墨里的错配方你闻不出来。爆炸按原计划发生，眉毛按原计划减少。",
         {"int": 1, "cha": -1}),
        (7181, "workshop_claim",
         "工位被占。你没有尺可以放在桌上。拳头也没能把工位要回来。",
         {"str": 1, "con": 1}),
        (7182, "chapel_watch",
         "圣堂夜盗走了侧门。你睡在另一侧。蜡烛替你值了班。",
         {"con": 1}),
        (7183, "relic_keeper",
         "圣物要人守。没有人把尘交给你。有人把圣物交给了更会说话的人。",
         {"cha": 1}),
        (7184, "line_officer",
         "临时编制把你写成列兵。锅是冷的，逃兵是真的。",
         {"con": 1, "wis": 1}),
        (7185, "trade_credit",
         "你的名字当不了押金。这一次要现银，下一袋货走了别的车。",
         {"gold": -1, "int": 1}),
        (7186, "harvest_hands",
         "雨前麦没收完。你不是那双被记住的手。仓空了一角。",
         {"con": 1}),
        (7187, "alley_debt",
         "有人来讨旧人情。你不欠这条巷子。巷子也不让你。",
         {"wis": 1, "agi": 1}),
        (7188, "retainer_name",
         "旧家臣从你身边走过，称呼是通用的先生。酒钱你仍付了。",
         {"gold": -1, "cha": 1}),
        (7189, "hunt_totem",
         "图腾朝着错误的方向。兽没有绕开帐篷。你学会了把火烧得更亮。",
         {"str": 1, "con": 1}),
    ]
    for eid, flag, desc, fx in false_reads:
        add({
            "eventId": eid, "desc": desc,
            "minAge": 16, "maxAge": 75, "baseWeight": 3, "maxTriggers": 2,
            "requiredFlags": [{flag: False}],
            "effects": fx,
            "cooldownGroups": [f"hg_{flag}_no"],
            "cooldownMinInterval": 8,
        })
