# -*- coding: utf-8 -*-
"""50 item flags + 50 skill/spell flags, with get / lose / use events."""
from __future__ import annotations


def _d0(*eids: int) -> list[dict]:
    return [{"eventId": i, "delay": 0} for i in eids]


def _ge(attr: str, n: int) -> dict:
    return {attr: {"operator": ">=", "value": n}}


def apply_gear(add, job_req, w_attr) -> None:
    _build(add, job_req, w_attr, ITEMS, kind="item")
    _build(add, job_req, w_attr, SKILLS, kind="skill")


def _build(add, job_req, w_attr, rows: list[dict], *, kind: str) -> None:
    if kind == "item":
        src_base, get_base, lose_parent, lose_base, use_base, walk = 5200, 5220, 5360, 5370, 5500, 5218
        src_cd, use_cd = "gear_shop", "item_use"
        walk_desc = "你把货看完，把钱数完，把念头也数完。空手离开也是一种决定。"
        lose_desc = "你清点行囊，少了一件不该少的东西。"
        src_age = (16, 60)
        lose_age = (17, 75)
    else:
        src_base, get_base, lose_parent, lose_base, use_base, walk = 5280, 5300, 5361, 5440, 5560, 5298
        src_cd, use_cd = "lesson", "skill_use"
        walk_desc = "先生看了你一眼：今天不是你的日子。学费退了一半，半句也没教。"
        lose_desc = "有些招式会从手上溜走，像水从拳缝里走。"
        src_age = (16, 45)
        lose_age = (20, 85)

    n = len(rows)
    get_ids = [get_base + i for i in range(n)]
    lose_ids = [lose_base + i for i in range(n)]
    use_ids = [use_base + i for i in range(n)]

    add({
        "eventId": walk, "desc": walk_desc,
        "minAge": src_age[0], "maxAge": src_age[1],
        "naturalUnlock": False, "baseWeight": 5, "effects": {"wis": 1},
    })

    sources = _sources(kind)
    for i, (title, indexes) in enumerate(sources):
        kids = [get_ids[j] for j in indexes] + [walk]
        add({
            "eventId": src_base + i, "desc": title,
            "minAge": src_age[0], "maxAge": src_age[1],
            "maxTriggers": 5, "baseWeight": 5,
            "cooldownGroups": [src_cd, "flag_fork"],
            "cooldownMinInterval": 6,
            "followUp": _d0(*kids),
            "ageModifiers": {"peak": 28, "decay": 0.96},
        })

    lose_req = [{row["flag"]: True} for row in rows]
    add({
        "eventId": lose_parent, "desc": lose_desc,
        "minAge": lose_age[0], "maxAge": lose_age[1],
        "maxTriggers": 4, "baseWeight": 4,
        "requiredFlags": lose_req,
        "cooldownGroups": [f"{kind}_loss"],
        "cooldownMinInterval": 9,
        "followUp": _d0(*lose_ids),
    })

    for i, row in enumerate(rows):
        flag = row["flag"]
        jobs = row.get("jobs")
        extra_or = list(row.get("or_flags") or [])
        req = []
        if jobs:
            req.extend(job_req(*jobs))
        req.extend(extra_or)
        get_ev = {
            "eventId": get_ids[i],
            "desc": row["get"],
            "minAge": src_age[0], "maxAge": 70,
            "naturalUnlock": False,
            "baseWeight": 14,
            "effects": dict(row["get_fx"]),
            "flags": {flag: True},
            "maxTriggers": 4 if row.get("consume") else 1,
        }
        if req:
            get_ev["requiredFlags"] = req
        gold = int(row.get("gold") or 0)
        if gold:
            get_ev["requiredAttrs"] = _ge("gold", gold)
            get_ev["weightModifiers"] = [w_attr("gold", gold, 2, 0.2)]
        add(get_ev)

        add({
            "eventId": lose_ids[i],
            "desc": row["lose"],
            "minAge": lose_age[0], "maxAge": 90,
            "naturalUnlock": False, "baseWeight": 12,
            "requiredFlags": [{flag: True}],
            "flags": {flag: None},
            "effects": dict(row["lose_fx"]),
            "maxTriggers": 3,
        })

        use_ev = {
            "eventId": use_ids[i],
            "desc": row["use"],
            "minAge": 16, "maxAge": 85,
            "baseWeight": 5, "maxTriggers": 1 if row.get("consume") else 4,
            "requiredFlags": [{flag: True}],
            "effects": dict(row["use_fx"]),
            "cooldownGroups": [use_cd, row.get("use_cd") or kind],
            "cooldownMinInterval": 5,
        }
        if row.get("consume") or row.get("clear"):
            cleared = {flag: None}
            for extra in row.get("clear") or ():
                cleared[extra] = None
            use_ev["flags"] = cleared
        extra_use = row.get("use_or")
        if extra_use:
            use_ev["requiredFlags"] = [{flag: True, **extra_use}]
        add(use_ev)


def _sources(kind: str) -> list[tuple[str, list[int]]]:
    if kind == "item":
        return [
            ("武器摊把刀剑摆成一行。你的手比眼睛先做决定。", [0, 1, 2, 3, 4]),
            ("防具匠敲敲你的肩：穿得住，才叫活得住。", [5, 6, 7, 8, 9]),
            ("工具行的抽屉比柜台深。有些东西不摆出来，只问你会不会用。", [10, 11, 12, 13, 14]),
            ("药摊的气味先把你拦住。瓶子上的字有真有假。", [15, 16, 17, 18, 19]),
            ("地城角落有一只没上锁的箱子。上锁的往往更空。", [20, 21, 22, 23, 24]),
            ("文书柜的钥匙在书记官枕头下。纸比剑更会伤人。", [25, 26, 27, 28, 29]),
            ("神龛前有人把不用的圣物放下。你也可以放下，或拿起。", [30, 31, 32, 33, 34]),
            ("黑市只点一盏灯。灯照得见货，照不见来处。", [35, 36, 37, 38, 39]),
            ("猎获摊把羽毛、牙和还在动的罐子摆在一起。", [40, 41, 42, 43, 44]),
            ("路边有一堆不该捡的东西。它们倒像在等你。", [45, 46, 47, 48, 49]),
        ]
    return [
        ("校场的沙土进了牙缝。教头说：先学会不倒下。", [0, 1, 2, 3, 4]),
        ("法师塔的楼梯比咒文长。有人在半层开始教你第一句。", [5, 6, 7, 8, 9]),
        ("神殿侧厅不收香火，只收专心。烛火把音节烤热。", [10, 11, 12, 13, 14]),
        ("林地里没有黑板。藤蔓和鸟替先生画重点。", [15, 16, 17, 18, 19]),
        ("盗贼行会的口令是一句脏话。说对了，才教你更脏的手艺。", [20, 21, 22, 23, 24]),
        ("酒馆后台把舞台当课堂。走调的人付酒钱，走对的人领新歌。", [25, 26, 27, 28, 29]),
        ("武馆的木人比你更有耐心。它倒了，你才算学会一招。", [30, 31, 32, 33, 34]),
        ("书斋不许出声。先生用口型教你读别人的口型。", [35, 36, 37, 38, 39]),
        ("作坊的火花是学费。烫一下，记一年。", [40, 41, 42, 43, 44]),
        ("禁书或噩梦都收费。你付了，它们才肯把句子说完。", [45, 46, 47, 48, 49]),
    ]


# gold: shop cost (0 = loot / gift). jobs/or_flags gate the acquire leaf.
ITEMS = [
    dict(flag="item_silver_blade", gold=5, jobs=("fighter", "paladin", "rogue", "ranger"),
         get="你买下一柄银刃短剑。店主说它不杀同类，只杀该杀的。",
         get_fx={"gold": -5, "str": 1},
         lose="银刃短剑在河里挣脱刀鞘。银光沉下去，像一句不肯回来的誓言。",
         lose_fx={"wis": 1, "cha": -1},
         use="你抽出银刃。不洁的东西先退了一步，人还没退。",
         use_fx={"str": 1, "wis": 1}, use_cd="combat"),
    dict(flag="item_oak_bow", gold=5, jobs=("ranger", "fighter", "rogue"),
         get="你试了三张弓。黑橡木那张在你手里像认识你的肩。",
         get_fx={"gold": -5, "agi": 1},
         lose="弓弦在雨里烂断。你把它埋在树下，像埋一位不再说话的同伴。",
         lose_fx={"wis": 1},
         use="四十步外你先结束战斗。近处的人还在找你的影子。",
         use_fx={"agi": 1, "int": 1}, use_cd="combat"),
    dict(flag="item_twin_axe", gold=6, jobs=("barbarian", "fighter"),
         get="双头斧比你的脾气还直。你付钱时，木桩已经少了一截。",
         get_fx={"gold": -6, "str": 1},
         lose="有一头斧刃卡在门里。你带走门，没带走斧。门比斧响。",
         lose_fx={"str": -1, "con": 1},
         use="你让双头斧转起来。盾牌选择了让路。",
         use_fx={"str": 1, "con": -1}, use_cd="combat"),
    dict(flag="item_rapier", gold=5, jobs=("fighter", "bard", "rogue", "paladin"),
         get="决斗刺剑很轻。店主说轻的东西更要求你站得直。",
         get_fx={"gold": -5, "agi": 1, "cha": 1},
         lose="刺剑被人当赌注赢走。你还在数规则，规则已经结束。",
         lose_fx={"cha": -1, "gold": -1},
         use="你把剑尖停在对方咽喉前一指。诗会有的，血可以没有。",
         use_fx={"agi": 1, "cha": 1}, use_cd="arena"),
    dict(flag="item_iron_spear", gold=4,
         get="铁头矛不讲究出身。你试了扎法，木人点头。",
         get_fx={"gold": -4, "str": 1},
         lose="矛杆被马踩断。你改用半截当手杖，手杖不会扎人。",
         lose_fx={"con": 1},
         use="长矛把距离变成你的。扑上来的人先认识铁，再认识你。",
         use_fx={"str": 1, "agi": 1}, use_cd="combat"),
    dict(flag="item_scale_mail", gold=7, jobs=("fighter", "paladin", "ranger", "cleric"),
         get="鳞甲合身。匠人说：盔甲的工作是让你有机会做别的工作。",
         get_fx={"gold": -7, "con": 1},
         lose="鳞甲在渡河时沉了。你浮上来，甲没有。",
         lose_fx={"con": -1, "str": 1},
         use="箭在鳞上滑开。你第一次感谢自己看起来像一条笨龙。",
         use_fx={"con": 1}, use_cd="combat"),
    dict(flag="item_shadow_cloak", gold=6, jobs=("rogue", "ranger", "warlock", "bard"),
         get="隐斗篷在灯下仍像没洗干净。你一披上，灯也懒得解释。",
         get_fx={"gold": -6, "agi": 1},
         lose="斗篷被风拿去当旗帜。旗帜没有秘密，秘密没有你。",
         lose_fx={"agi": -1, "cha": 1},
         use="你走进亮处，仍有人问：谁刚刚过去了？",
         use_fx={"agi": 1, "int": 1}, use_cd="crime"),
    dict(flag="item_lucky_ring", gold=4,
         get="幸运铜戒不发光。戴上的瞬间骰子自己立住，又自己倒下去。",
         get_fx={"gold": -4, "cha": 1},
         lose="铜戒从指缝滚进下水道。幸运去了它该去的地方。",
         lose_fx={"cha": -1},
         use="你本该踩空。戒指轻轻一烫，你改踩实处。",
         use_fx={"agi": 1, "gold": 1}, use_cd="money"),
    dict(flag="item_iron_boots", gold=4, jobs=("fighter", "paladin", "monk", "barbarian"),
         get="铁靴重。你走了十步，步伐开始像你自己的。",
         get_fx={"gold": -4, "con": 1},
         lose="一只铁靴陷进沼泽。你赤一脚走完今年，记得每一寸泥。",
         lose_fx={"con": 1, "agi": -1},
         use="你把铁靴砸在盾面上。盾面同意谈判。",
         use_fx={"str": 1, "con": 1}, use_cd="combat"),
    dict(flag="item_deer_gloves", gold=3, jobs=("ranger", "rogue", "druid", "monk"),
         get="鹿皮手套让弓弦不再咬手。兽也不再那么讨厌你的气味。",
         get_fx={"gold": -3, "agi": 1},
         lose="手套被营火烤焦。你的手重新认识茧。",
         lose_fx={"con": 1},
         use="你徒手从荆棘里抽出箭。手没破，荆棘破了。",
         use_fx={"agi": 1, "wis": 1}, use_cd="wilderness"),
    dict(flag="item_thief_tools", gold=4, jobs=("rogue",),
         get="开锁工具一套。师傅说：能开的锁，最好先问问该不该开。",
         get_fx={"gold": -4, "int": 1},
         lose="工具被卫兵当罪证收走。锁还在，罪证比锁硬。",
         lose_fx={"cha": -1, "int": 1},
         use="你把锁打开又锁上。主人回来时它还在，你已经不在。",
         use_fx={"agi": 1, "int": 1, "gold": 2}, use_cd="crime"),
    dict(flag="item_alembic", gold=5, jobs=("wizard", "rogue", "cleric"),
         get="炼金蒸馏器占了半张桌子。第一瓶蒸馏水尝起来像道歉。",
         get_fx={"gold": -5, "int": 1},
         lose="蒸馏器炸了一角。你学会了先开窗，再点火，但器具没了。",
         lose_fx={"con": -1, "int": 1},
         use="你把污泥蒸成能喝的东西。能喝不等于想喝。",
         use_fx={"int": 1, "con": 1}, use_cd="craft"),
    dict(flag="item_miner_lamp", gold=3,
         get="矿工提灯在白天也亮。卖灯的人说：黑比穷更先到。",
         get_fx={"gold": -3, "wis": 1},
         lose="提灯在井里灭了。你摸着墙上来，墙比灯诚实。",
         lose_fx={"con": 1},
         use="你把灯伸进洞口。洞口里的眼睛先闭上。",
         use_fx={"wis": 1, "int": 1}, use_cd="dungeon"),
    dict(flag="item_star_astrolabe", gold=6, jobs=("wizard", "ranger", "bard"),
         get="航海星盘比你的数学好。你买下它，把北从猜测改成测量。",
         get_fx={"gold": -6, "int": 1},
         lose="星盘被海关当禁器扣下。星还在，盘不在。",
         lose_fx={"int": 1, "gold": -1},
         use="雾里你不靠路标。星盘把你带出一张会吃人的地图。",
         use_fx={"int": 1, "agi": 1}, use_cd="sea"),
    dict(flag="item_craft_hammer", gold=4, or_flags=[{"origin": "artisan"}],
         get="工匠锤很旧。旧到能把新铁训明白。",
         get_fx={"gold": -4, "str": 1},
         lose="锤头飞进河里。你用石头收尾，石头不署名。",
         lose_fx={"str": -1, "con": 1},
         use="你把断掉的门轴敲回去。城门重新会鞠躬。",
         use_fx={"str": 1, "gold": 2}, use_cd="craft"),
    dict(flag="item_heal_potion", gold=3, consume=True,
         get="治疗药水沉在瓶底像红糖。卖药的人说：痛的时候再喝，甜的时候别喝。",
         get_fx={"gold": -3},
         lose="药水瓶在包里碎了。你的衬衫好了，你没有。",
         lose_fx={"con": -1, "cha": -1},
         use="你把治疗药水喝干。伤口先相信它，你后相信。",
         use_fx={"con": 2}, use_cd="heal"),
    dict(flag="item_invis_phial", gold=5, consume=True, jobs=("rogue", "wizard", "warlock"),
         get="隐身药看起来像清水。店主让你对着镜子试一滴，镜子礼貌地空白了一息。",
         get_fx={"gold": -5},
         lose="隐身药被小孩当成糖水喝了。小孩还在，药不在，你开始解释。",
         lose_fx={"cha": -1, "wis": 1},
         use="你把隐身药抹上喉咙。卫兵点了你三次名，点到空气。",
         use_fx={"agi": 1, "int": 1}, use_cd="crime"),
    dict(flag="item_antitoxin", gold=3, consume=True,
         get="抗毒剂苦得像把药园嚼了一遍。你仍买下，因为甜的往往来不及。",
         get_fx={"gold": -3},
         lose="抗毒剂过期结块。你把它埋了，像埋一次没发生的中毒。",
         lose_fx={"wis": 1},
         use="毒线爬到肘弯时你喝下抗毒剂。苦赢了，黑线输了。",
         use_fx={"con": 1}, clear=("poisoned",), use_cd="heal"),
    dict(flag="item_rage_phial", gold=4, consume=True, jobs=("barbarian", "fighter"),
         get="狂暴药剂在瓶里自己晃。店主用铁匣装着卖，像卖一头还没同意的兽。",
         get_fx={"gold": -4},
         lose="药剂洒在篝火上。火暴了一会儿，你没有。",
         lose_fx={"con": -1},
         use="你喝下狂暴药剂。痛迟到了，力先到。",
         use_fx={"str": 2, "wis": -1}, use_cd="combat"),
    dict(flag="item_sleep_dust", gold=3, consume=True, jobs=("rogue", "bard", "wizard"),
         get="睡眠粉装在纸包里。店主打了个哈欠当广告。",
         get_fx={"gold": -3},
         lose="纸包被风吹散。半个营地提前睡觉，你提前守夜。",
         lose_fx={"con": 1, "cha": -1},
         use="你把睡眠粉撒进岗哨的汤。岗哨做了一个很长的、没有你的梦。",
         use_fx={"agi": 1, "int": 1}, use_cd="crime"),
    dict(flag="item_talking_skull", gold=0, jobs=("wizard", "warlock", "cleric", "bard"),
         get="能说话的骷髅在箱子里骂你手慢。你把它带上，它改骂路。",
         get_fx={"int": 1, "cha": 1},
         lose="骷髅被人当成普通骨头埋了。它最后一句是：我还有话。",
         lose_fx={"wis": 1, "cha": -1},
         use="骷髅替你回忆一段你没在场的历史。真假各半，有用的那半刚好够。",
         use_fx={"int": 1, "wis": 1}, use_cd="undead"),
    dict(flag="item_path_compass", gold=0,
         get="寻路罗盘不指北，指‘还活着的出口’。你试了一次，出口是一扇窗。",
         get_fx={"wis": 1},
         lose="罗盘在磁铁矿脉旁疯转，直到针掉出来。方向重新变回猜测。",
         lose_fx={"int": -1, "wis": 1},
         use="迷雾里罗盘轻轻偏了一度。你跟着偏，避开一张会吃人的路。",
         use_fx={"wis": 1, "agi": 1}, use_cd="dungeon"),
    dict(flag="item_fold_boat", gold=0,
         get="折叠舟像一张厚皮。说明书只有一句：湿了才会承认自己是船。",
         get_fx={"int": 1},
         lose="舟在急流里展开得太彻底，再折不回去。你上岸，它去看海。",
         lose_fx={"con": 1, "wis": 1},
         use="河水比桥快。你把皮一抖，船自己鼓起来。对岸的人开始重新计算你。",
         use_fx={"agi": 1, "con": 1}, use_cd="sea"),
    dict(flag="item_endless_sack", gold=0,
         get="无尽粮袋永远有一块硬面包。硬，但无穷。你咬第一口时差点谢神。",
         get_fx={"con": 1},
         lose="粮袋被老鼠敬为神殿。神殿被你拆了，袋子也空了。",
         lose_fx={"con": -1, "gold": -1},
         use="围城第三天你打开粮袋。面包仍在。士气比面包先软，又硬回来。",
         use_fx={"con": 1, "cha": 1}, use_cd="war"),
    dict(flag="item_memory_crystal", gold=0, jobs=("wizard", "sorcerer", "warlock", "bard"),
         get="记忆水晶里封着别人的一天。你不敢先看完，怕把自己过成那一天。",
         get_fx={"int": 1},
         lose="水晶裂了。一天的记忆变成一地没人认领的亮。",
         lose_fx={"wis": 1, "int": -1},
         use="你把水晶贴上额。别人的失败替你付了一次学费。",
         use_fx={"int": 2}, use_cd="library"),
    dict(flag="item_pardon", gold=4, or_flags=[{"origin": "noble"}, {"in_guild": True}],
         get="赦免状盖着模糊的印。模糊有时比清晰更像真的。",
         get_fx={"gold": -4, "cha": 1},
         lose="赦免状被雨泡开。印还在，字先走了。",
         lose_fx={"cha": -1},
         use="绞架下你展开赦免状。绳子停住，像突然识字。",
         use_fx={"cha": 2, "wis": 1}, use_cd="crime"),
    dict(flag="item_noble_letter", gold=5, or_flags=[{"origin": "noble"}, {"origin": "merchant"}],
         get="贵族荐信只有三行，第三行是姓。姓比内容贵。",
         get_fx={"gold": -5, "cha": 1},
         lose="荐信被当成引火纸。火很旺，门没开。",
         lose_fx={"cha": -1, "int": 1},
         use="门房看见姓，少问了三句，多敬了一寸。",
         use_fx={"cha": 1, "gold": 1}, use_cd="court"),
    dict(flag="item_fake_papers", gold=4, jobs=("rogue", "bard", "warlock"),
         get="假身份文书把你写成另一个人的亲戚。那个人如果存在，大概不会认你。",
         get_fx={"gold": -4, "int": 1},
         lose="文书在关卡对不上眼色。你把它吞了。纸很苦，人还在。",
         lose_fx={"con": -1, "int": 1},
         use="你用假身份住进不该住的客栈。账单是真的，名字是假的。",
         use_fx={"int": 1, "agi": 1, "gold": -1}, use_cd="crime"),
    dict(flag="item_map_scrap", gold=0,
         get="藏宝残页只剩齿痕边。缺口处写着：另一半会咬人。",
         get_fx={"int": 1},
         lose="残页被火塘卷走。灰里隐约还有齿痕。",
         lose_fx={"wis": 1},
         use="你按残页避开三处假标记。第四处是真的，真的只是一口井。",
         use_fx={"int": 1, "gold": 2}, use_cd="artifact"),
    dict(flag="item_pact_copy", gold=0, jobs=("warlock", "wizard"),
         get="魔契抄本缺了签字页。缺页的合同有时比完整的更危险。",
         get_fx={"int": 1, "cha": 1},
         lose="抄本自己烧掉，留下一句：下次用真的。",
         lose_fx={"wis": 1, "cha": -1},
         use="你把抄本拍在谈判桌上。对方先改了价钱，再问你是不是那个人。",
         use_fx={"cha": 1, "int": 1, "gold": 3}, use_cd="weird"),
    dict(flag="item_holy_water", gold=3, jobs=("cleric", "paladin"), or_flags=[{"faith": True}],
         get="圣水瓶比酒壶轻。神父说：洒比喝重要，喝了也不算亵渎，只算浪费。",
         get_fx={"gold": -3, "wis": 1},
         lose="圣水在颠簸里洒光。瓶子还在，空比满更响。",
         lose_fx={"wis": 1},
         use="你把圣水洒在伤口和门槛上。血味淡了，门槛也老实了。",
         use_fx={"wis": 1, "con": 1}, use_cd="church"),
    dict(flag="item_druid_seed", gold=0, jobs=("druid", "ranger"), or_flags=[{"origin": "tribe"}],
         get="德鲁伊种子在掌心发烫。有人说种下去会记得你，有人说会审判你。",
         get_fx={"wis": 1},
         lose="种子发芽在你的口袋里。你把它连布一起埋了，布也长了一片叶。",
         lose_fx={"wis": 1, "con": 1},
         use="你把种子按进裂开的城墙。藤蔓连夜把裂口缝上，像缝一件旧衣。",
         use_fx={"wis": 1, "con": 1, "cha": 1}, use_cd="wilderness"),
    dict(flag="item_dragon_scale", gold=0,
         get="龙鳞碎片还热。你不敢问龙是否同意捐赠。",
         get_fx={"con": 1, "cha": 1},
         lose="鳞片被收藏家用三倍价买走。他的眼睛比龙热。",
         lose_fx={"gold": 6, "cha": -1},
         use="你把龙鳞垫在盾后。火滑开了，眉毛差点没有。",
         use_fx={"con": 1, "str": 1}, use_cd="dungeon"),
    dict(flag="item_fey_bell", gold=0, jobs=("bard", "druid", "warlock", "sorcerer"),
         get="妖精银铃不响给不该听的人。你试了一次，林子回了一句谢谢。",
         get_fx={"cha": 1},
         lose="银铃被小孩拿去当玩具。林子从此对你客气得像对陌生人。",
         lose_fx={"cha": -1, "wis": 1},
         use="你摇铃。岔路里的雾让开一尺，够一只脚，不够两只谎言。",
         use_fx={"cha": 1, "wis": 1}, use_cd="fey"),
    dict(flag="item_dead_coin", gold=0, jobs=("cleric", "warlock", "rogue"),
         get="亡者硬币一面是脸，一面是门。你把它留在舌下试了试，门没有开。",
         get_fx={"wis": 1},
         lose="硬币被渡工收走。他说这才是正规票价，你的命是找零。",
         lose_fx={"wis": 1, "gold": -1},
         use="你把亡者硬币放在死者眼睛上。死者没有起来，只是看起来像睡着。",
         use_fx={"wis": 1, "cha": 1}, use_cd="undead"),
    dict(flag="item_coin_mold", gold=3, jobs=("rogue",), or_flags=[{"origin": "street"}, {"origin": "merchant"}],
         get="假币模具冰凉。铸币人说：只做一次叫试，做两次叫职业。",
         get_fx={"gold": -3, "int": 1},
         lose="模具被税吏踩扁。扁得像一份警告。",
         lose_fx={"cha": -1, "int": 1},
         use="你浇了一枚假币又把它熔掉。手艺还在，罪证少了一枚。",
         use_fx={"int": 1, "gold": 2}, use_cd="crime"),
    dict(flag="item_run_purse", gold=4,
         get="会跑的钱袋在柜上自己挪了一寸。店主说它认主，也认更快的腿。",
         get_fx={"gold": -4, "agi": 1},
         lose="钱袋自己跑了。它比你更理解自由。",
         lose_fx={"gold": -3, "agi": 1},
         use="窃贼摸到你的袋。袋先跑，贼后摔。金币笑了一下。",
         use_fx={"agi": 1, "gold": 1}, use_cd="money"),
    dict(flag="item_tax_stamp", gold=5, or_flags=[{"origin": "noble"}, {"origin": "merchant"}, {"in_guild": True}],
         get="税吏印章不该出现在黑市。你买下它，像买下一句能开门的脏话。",
         get_fx={"gold": -5, "int": 1},
         lose="印章被真正的税吏认出来。他没收印章，留下一份真正的税。",
         lose_fx={"gold": -4, "cha": -1},
         use="关卡要税。你盖章。章比钱快，心比章虚。",
         use_fx={"gold": 3, "int": 1, "cha": -1}, use_cd="money"),
    dict(flag="item_pearl_ear", gold=6, or_flags=[{"origin": "noble"}, {"job": "bard"}],
         get="珍珠耳坠像一滴不肯落地的海。戴上它，有人开始愿意听完你的句子。",
         get_fx={"gold": -6, "cha": 1},
         lose="耳坠被舞会上的手摘走。手很美，动作很职业。",
         lose_fx={"cha": -1, "agi": 1},
         use="你戴上珍珠耳坠去求见。门房的眼睛先软，门后软。",
         use_fx={"cha": 2}, use_cd="court"),
    dict(flag="item_ivory_chess", gold=5, jobs=("wizard", "bard", "rogue", "monk"),
         get="象牙棋少一卒。卖棋的人说缺的那枚在赢家口袋里。",
         get_fx={"gold": -5, "int": 1},
         lose="棋被小孩当成积木。王车易位变成倒塌。",
         lose_fx={"wis": 1, "int": -1},
         use="你用残棋逼和一位将军。他输的是面子，你赢的是一条路条。",
         use_fx={"int": 1, "cha": 1}, use_cd="court"),
    dict(flag="item_phoenix_feather", gold=0, jobs=("sorcerer", "wizard", "druid", "cleric"),
         get="凤凰羽毛在匣里自己亮。你碰它时，旧伤疤痒了一下。",
         get_fx={"cha": 1, "con": 1},
         lose="羽毛燃成一缕没有烟的红。红很短，暖很长。",
         lose_fx={"wis": 1, "con": 1},
         use="你把羽毛按在濒死的人胸口。心跳回来时，羽毛少了一撮光。",
         use_fx={"wis": 1, "cha": 1, "con": 1}, use_cd="heal"),
    dict(flag="item_basilisk_eye", gold=0, jobs=("wizard", "ranger", "warlock"),
         get="石化蜥眼泡在醋里。店主用铁夹递给，像递一块会看人的冰。",
         get_fx={"int": 1, "wis": 1},
         lose="眼睛被阳光晒干，变成普通的石珠。它不再看你，你反而有点想念。",
         lose_fx={"wis": 1},
         use="你把蜥眼对着追兵一晃。追兵的左脚先犹豫成了石头，右脚还在跑。",
         use_fx={"int": 1, "cha": 1}, use_cd="weird"),
    dict(flag="item_hive_jar", gold=2, jobs=("druid", "ranger"), or_flags=[{"origin": "farmer"}],
         get="蜂巢罐里有还在工作的蜂。卖家说它们认花，也认你袖口的糖。",
         get_fx={"gold": -2, "wis": 1},
         lose="罐子摔开。蜂去了该去的花，你肿了该肿的手。",
         lose_fx={"con": -1, "cha": 1},
         use="你放蜂去驱散马贼。马贼比马先认识刺。",
         use_fx={"wis": 1, "cha": 1}, use_cd="wilderness"),
    dict(flag="item_owl_whistle", gold=3, jobs=("ranger", "rogue", "wizard", "druid"),
         get="夜枭哨吹出来不像哨，像一句很短的夜。",
         get_fx={"gold": -3, "wis": 1},
         lose="哨被小孩吹破。夜还在，只是不再回你。",
         lose_fx={"wis": 1},
         use="你吹哨。林子里有翅膀替你看完一圈岗哨，回来时羽毛里夹着一根线。",
         use_fx={"wis": 1, "int": 1}, use_cd="wilderness"),
    dict(flag="item_wolf_tooth", gold=2, jobs=("barbarian", "ranger", "druid"), or_flags=[{"origin": "tribe"}],
         get="狼牙项链还带着雪味。族里的人说戴上它，狼会把你算进人数。",
         get_fx={"gold": -2, "str": 1},
         lose="项链在搏斗里崩开。牙散了一地，像一场没有赢家的投票。",
         lose_fx={"cha": -1, "str": 1},
         use="野狼围上来。你把牙亮给它们看。它们把你从菜单上划掉。",
         use_fx={"wis": 1, "cha": 1, "con": 1}, use_cd="wilderness"),
    dict(flag="item_thirst_dagger", gold=0, jobs=("warlock", "rogue", "barbarian"),
         get="渴血匕首在布里自己润湿。你不该捡。你捡了。",
         get_fx={"str": 1, "wis": -1},
         lose="教会把匕首收进铁匣。匣子在夜里出汗。",
         lose_fx={"wis": 1, "cha": 1},
         use="匕首喝到第一滴时变轻。你的手变重，像欠了它下一次。",
         use_fx={"str": 1, "con": -1, "cha": -1}, use_cd="crime"),
    dict(flag="item_whisper_mask", gold=0, jobs=("warlock", "bard", "rogue", "sorcerer"),
         get="耳语面具内侧刻满别人的名字。你戴上试音，听见自己的名字被轻轻拼错。",
         get_fx={"cha": 1, "int": 1},
         lose="面具被风摘走，挂在树上像一张没有主人的脸。",
         lose_fx={"cha": -1, "wis": 1},
         use="你戴上面具说话。听众点头，像点给另一个更会说的人。",
         use_fx={"cha": 2, "wis": -1}, use_cd="social"),
    dict(flag="item_black_candle", gold=2, jobs=("warlock", "cleric", "wizard"),
         get="黑蜡蜡烛点燃时没有香。有人说它照的是已经不在的座位。",
         get_fx={"gold": -2, "wis": 1},
         lose="蜡烛燃到铁芯。铁芯像一枚钉子，把夜钉死了一角。",
         lose_fx={"wis": 1},
         use="你在黑蜡烛下问一句已经没法回答的话。蜡油里浮出半个字，刚好够用。",
         use_fx={"wis": 1, "int": 1}, use_cd="undead"),
    dict(flag="item_upside_glass", gold=0, jobs=("wizard", "warlock", "monk"),
         get="倒吊沙漏的沙子往上走。你看了一息，觉得自己的下午被谁借走了。",
         get_fx={"int": 1, "wis": 1},
         lose="沙漏摔碎。时间恢复下流，你的膝盖先感到年纪。",
         lose_fx={"con": -1, "wis": 1},
         use="你把沙漏倒过来。追兵的一步被拉长成两步，你的一步变成门闩。",
         use_fx={"agi": 1, "int": 1}, use_cd="weird"),
    dict(flag="item_nameless_ash", gold=0, jobs=("warlock", "cleric", "wizard"),
         get="无名骨灰罐没有铭文。拿起来时，周围的狗同时不叫了。",
         get_fx={"wis": 1, "cha": -1},
         lose="你把骨灰撒进河。河走了，狗重新开始叫。",
         lose_fx={"cha": 1, "wis": 1},
         use="你撒出一撮无名骨灰。亡灵把你当成自己人，活人把你当成错误。",
         use_fx={"wis": 1, "int": 1, "cha": -1}, use_cd="undead"),
]


SKILLS = [
    dict(flag="skill_shield_bash", gold=0, jobs=("fighter", "paladin", "cleric"),
         get="教头让你用盾去撞木人，直到木人先认输。你学会了盾击。",
         get_fx={"str": 1, "con": 1},
         lose="肩伤让你不敢再把盾当锤子。盾回去做盾，你回去做人。",
         lose_fx={"con": -1, "wis": 1},
         use="你把盾面送进对方的呼吸。号角还没落，缺口已经补上。",
         use_fx={"str": 1, "con": 1}, use_cd="combat"),
    dict(flag="skill_double_cut", gold=0, jobs=("fighter", "ranger", "rogue", "paladin"),
         get="双连斩的第二刀发生在第一刀被当成结束的时候。你练到肌肉自己记得。",
         get_fx={"str": 1, "agi": 1},
         lose="你在病中把节奏忘了。第一刀还在，第二刀变成喘气。",
         lose_fx={"str": -1, "wis": 1},
         use="对手格开第一刀，把胸口借给第二刀。他事后说那不算公平。",
         use_fx={"str": 1, "agi": 1}, use_cd="combat"),
    dict(flag="skill_throwing", gold=1, jobs=("rogue", "ranger", "fighter", "bard"),
         get="飞刀教头让你先打树。树没有意见。你学会了让金属走直线。",
         get_fx={"gold": -1, "agi": 1},
         lose="你的手腕在一次摔伤后不再听话。刀会飞，只是不再听你的。",
         lose_fx={"agi": -1, "con": 1},
         use="你在言语结束前让飞刀先到。言语因此变得更短、更诚实。",
         use_fx={"agi": 1, "int": 1}, use_cd="combat"),
    dict(flag="skill_trip", gold=0, jobs=("monk", "fighter", "rogue", "barbarian"),
         get="摔技从被摔开始。你站起来第七次时，地面开始怕你。",
         get_fx={"agi": 1, "str": 1},
         lose="膝盖积了水。你改回用手，脚不再是武器。",
         lose_fx={"con": -1, "wis": 1},
         use="你把面甲很高的骑士摔成一堆铁。铁很响，人在里面重新学习地面。",
         use_fx={"agi": 1, "str": 1}, use_cd="arena"),
    dict(flag="skill_sunder", gold=0, jobs=("fighter", "barbarian", "paladin"),
         get="破甲要打在甲片的缝上。你打了三百次缝，缝开始躲。",
         get_fx={"str": 1},
         lose="你的斧刃卷了。破甲变成砸甲，砸甲变成噪音。",
         lose_fx={"str": -1, "con": 1},
         use="你把对方的护胸打成两半。里面是人。人比甲便宜，也比甲肯谈。",
         use_fx={"str": 2, "cha": 1}, use_cd="combat"),
    dict(flag="skill_magic_missile", gold=2, jobs=("wizard", "sorcerer"),
         get="魔弹的音节像三颗石子。你念对时，石子自己找到靶心。你学会了魔弹。",
         get_fx={"gold": -2, "int": 1},
         lose="你发热把音节记成了菜谱。魔弹变成一句没有去处的热气。",
         lose_fx={"int": -1, "con": 1},
         use="三枚光弹绕开掩护，去敲那个最会躲的人。躲不再是策略。",
         use_fx={"int": 1, "cha": 1}, use_cd="magic"),
    dict(flag="skill_mage_armor", gold=2, jobs=("wizard", "sorcerer", "warlock"),
         get="法师护甲是一层看不见的固执。你学会让空气在你被砍之前先硬一下。",
         get_fx={"gold": -2, "int": 1, "con": 1},
         lose="护甲在一次过载后不再听话。空气重新变成空气。",
         lose_fx={"con": -1, "int": 1},
         use="刀在离皮肤一指处停住，像砍进冻住的水。你道谢，水不说话。",
         use_fx={"con": 1, "int": 1}, use_cd="magic"),
    dict(flag="skill_detect_illusion", gold=2, jobs=("wizard", "sorcerer", "bard", "warlock"),
         get="识破幻术的第一课是承认自己爱看假的。你仍学会了眨眼的时机。",
         get_fx={"gold": -2, "int": 1, "wis": 1},
         lose="你开始分不清哪次是术，哪次是累。识破变成一种多疑。",
         lose_fx={"wis": -1, "int": 1},
         use="桥是画。你没有走上去。画里的人很失望。",
         use_fx={"int": 1, "wis": 1}, use_cd="magic"),
    dict(flag="skill_grease", gold=1, jobs=("wizard", "sorcerer", "rogue"),
         get="油腻术让地面变成借口。你学会之后，台阶开始不信任你。",
         get_fx={"gold": -1, "int": 1},
         lose="你把材料配比忘成了厨房。地板很安全，敌人也很安全。",
         lose_fx={"int": -1, "wis": 1},
         use="追兵在油上跳了一支不情愿的舞。你先离开舞池。",
         use_fx={"int": 1, "agi": 1}, use_cd="magic"),
    dict(flag="skill_flash", gold=1, jobs=("wizard", "sorcerer", "cleric"),
         get="闪光术是一声没有礼貌的白天。你学会让它只亮一次，亮在该亮的眼里。",
         get_fx={"gold": -1, "int": 1, "cha": 1},
         lose="你的闪光越来越像咳嗽。敌人开始戴墨镜，你开始戴口罩。",
         lose_fx={"cha": -1, "int": 1},
         use="你在巷口打出闪光。弓手把箭送给墙壁，墙壁不还手。",
         use_fx={"int": 1, "agi": 1}, use_cd="magic"),
    dict(flag="skill_heal", gold=0, jobs=("cleric", "paladin", "druid", "bard"),
         get="疗伤术不是把血推回去，是让血记得该停在哪里。你学会了低声请求。",
         get_fx={"wis": 1, "cha": 1},
         lose="你的神一时不接。疗伤变成包扎，包扎仍然有用，只是不再发光。",
         lose_fx={"wis": -1, "con": 1},
         use="你把掌心贴上伤口。热度退了，像有人把门轻轻关上。",
         use_fx={"wis": 1, "con": 1, "cha": 1}, use_cd="heal"),
    dict(flag="skill_turn_undead", gold=0, jobs=("cleric", "paladin"),
         get="驱散亡灵要先站直。你站直时，腐气自己往后退，像退让一位还活着的人。",
         get_fx={"wis": 1, "cha": 1},
         lose="一次失败的驱散让你开始发抖。亡灵闻见抖，比闻见血快。",
         lose_fx={"cha": -1, "wis": 1},
         use="你举起圣徽。骷髅坐下，像突然想起自己已经下班。",
         use_fx={"wis": 1, "cha": 1}, use_cd="undead"),
    dict(flag="skill_bless", gold=0, jobs=("cleric", "paladin"), or_flags=[{"faith": True}],
         get="祝福是一句被烤热的名字。你学会把它说给还没倒下去的人听。",
         get_fx={"wis": 1, "cha": 1},
         lose="你把祷词说顺了，顺到没有重量。祝福变成客气。",
         lose_fx={"cha": -1, "wis": 1},
         use="出战前你祝福了三个人。三个人都回来了。第四个没要，你一整夜没睡。",
         use_fx={"cha": 1, "wis": 1}, use_cd="church"),
    dict(flag="skill_holy_light", gold=0, jobs=("cleric", "paladin", "sorcerer"),
         get="圣光从掌心漏出来时像你握不住的早晨。你学会握紧一点。",
         get_fx={"wis": 1, "con": 1},
         lose="光越来越像灯油。灯油能亮，只是不再让亡者害羞。",
         lose_fx={"wis": -1, "int": 1},
         use="你把圣光打进墓道。阴影里的牙先收起来。",
         use_fx={"wis": 1, "cha": 1}, use_cd="church"),
    dict(flag="skill_calm", gold=0, jobs=("cleric", "monk", "bard", "druid"),
         get="安宁术让怒火改坐。你对自己试了一次，拳头松开，像松开一只鸟。",
         get_fx={"wis": 1, "cha": 1},
         lose="你自己先不安宁。术还在书上，人不在书上。",
         lose_fx={"wis": -1, "con": 1},
         use="械斗的两边同时坐下。有人骂你扫兴。扫兴活着。",
         use_fx={"cha": 1, "wis": 1}, use_cd="social"),
    dict(flag="skill_beast_speech", gold=0, jobs=("druid", "ranger", "bard"),
         get="兽语的第一句是道歉。你学会后，乌鸦开始把你的谣言纠正过来。",
         get_fx={"wis": 1, "cha": 1},
         lose="你在城里把兽语说成了咳嗽。兽不再回信，咳嗽还在。",
         lose_fx={"cha": -1, "wis": 1},
         use="你问鹿哪条路没有铁。鹿用鼻子指出一条更湿、更对的路。",
         use_fx={"wis": 1, "agi": 1}, use_cd="wilderness"),
    dict(flag="skill_entangle", gold=0, jobs=("druid", "ranger"),
         get="纠缠藤听得懂‘现在’。你一指，地面就把脚踝当成作业。",
         get_fx={"wis": 1, "int": 1},
         lose="干季里藤不听。你的手指还在指，地是地。",
         lose_fx={"wis": -1, "con": 1},
         use="伏击的人被自己的踏点抓住。你从作业边上走过去，没有给分。",
         use_fx={"wis": 1, "str": 1}, use_cd="wilderness"),
    dict(flag="skill_water_walk", gold=0, jobs=("druid", "ranger", "cleric", "monk"),
         get="踏水不是漂，是让水暂时同意你的重量。你走了七步，第七步湿了鞋。",
         get_fx={"wis": 1, "agi": 1},
         lose="你在一次惊吓里把协议忘了。水重新成为水，你重新成为落水者。",
         lose_fx={"con": 1, "agi": -1},
         use="断桥对面有人。你从河面走过去。对方把神和骗子各怀疑了一半。",
         use_fx={"agi": 1, "cha": 1}, use_cd="sea"),
    dict(flag="skill_bird_message", gold=0, jobs=("druid", "ranger", "wizard", "bard"),
         get="传讯鸟要先喂。喂过之后，它把你的句子带去它愿意去的窗台。",
         get_fx={"wis": 1, "int": 1},
         lose="鸟不再来。你的信改回用腿。腿比翅膀诚实，也更慢。",
         lose_fx={"wis": 1, "con": 1},
         use="你把三句话交给一只雀。雀把最重要的那句送到，另外两句送给了猫。",
         use_fx={"int": 1, "cha": 1}, use_cd="wilderness"),
    dict(flag="skill_barkskin", gold=0, jobs=("druid", "ranger"),
         get="树肤让你痒了一夜。第二天刀在你手臂上打滑，像砍错了树。",
         get_fx={"con": 1, "wis": 1},
         lose="皮重新变软。你想念那种难看的安全。",
         lose_fx={"con": -1, "cha": 1},
         use="伏击的第一刀只削下一块皮屑。皮屑是树的，血还是你的，只是少了很多。",
         use_fx={"con": 1, "str": 1}, use_cd="wilderness"),
    dict(flag="skill_silent_step", gold=1, jobs=("rogue", "monk", "ranger"),
         get="沉默步从把铃铛绑在脚踝开始。铃铛不响那天，猫才承认你。",
         get_fx={"gold": -1, "agi": 1},
         lose="你在铁靴里把这招走丢了。地板重新认识你。",
         lose_fx={"agi": -1, "str": 1},
         use="你从守卫之间穿过。他们当时正在认真听一只并不存在的老鼠。",
         use_fx={"agi": 2}, use_cd="crime"),
    dict(flag="skill_lockpick", gold=1, jobs=("rogue",),
         get="开锁不是暴力，是说服金属。你说服了十二把锁，第十三把成为朋友。",
         get_fx={"gold": -1, "int": 1, "agi": 1},
         lose="手指被门夹过后不再精细。锁比你更有原则。",
         lose_fx={"agi": -1, "int": 1},
         use="你打开不该开的门，又把它锁上。里面的人以为自己做了梦。",
         use_fx={"agi": 1, "int": 1, "gold": 2}, use_cd="crime"),
    dict(flag="skill_disguise", gold=1, jobs=("rogue", "bard", "warlock"),
         get="易容从画自己的眉毛开始。你画到连镜子都愿意说谎。",
         get_fx={"gold": -1, "cha": 1, "int": 1},
         lose="有人当众揭了你的胶。胶比脸先落地。",
         lose_fx={"cha": -1, "wis": 1},
         use="你顶着一张温和的脸走进不温和的地方。门卫把你当成该进的人。",
         use_fx={"cha": 1, "int": 1}, use_cd="crime"),
    dict(flag="skill_shadow_hide", gold=0, jobs=("rogue", "ranger", "monk", "warlock"),
         get="影藏不是消失，是让眼睛觉得你不值得聚焦。你练到灯火开始偷懒。",
         get_fx={"agi": 1, "wis": 1},
         lose="你越来越想被看见。影子不合作。",
         lose_fx={"cha": 1, "agi": -1},
         use="搜查队从你身边过。有人说这儿有风。风没有被逮捕。",
         use_fx={"agi": 1, "int": 1}, use_cd="crime"),
    dict(flag="skill_poisoner", gold=2, jobs=("rogue",),
         get="下毒手法的第一课是洗手。第二课是还要再洗。你学会了剂量。",
         get_fx={"gold": -2, "int": 1},
         lose="你把剂量忘成了厨房。汤很香，人还醒着，你改行做菜。",
         lose_fx={"int": -1, "wis": 1, "cha": 1},
         use="酒里多了一滴。对方的剑先睡着，人后睡着。你把剑拿走，把人留下。",
         use_fx={"int": 1, "agi": 1}, use_cd="crime"),
    dict(flag="skill_war_song", gold=1, jobs=("bard", "paladin", "barbarian"),
         get="战歌要把胆写成节奏。你唱对时，旁边的人把步子踩进同一拍。",
         get_fx={"gold": -1, "cha": 1, "str": 1},
         lose="你的嗓子破了。战歌变成口气。口气没有编制。",
         lose_fx={"cha": -1, "con": 1},
         use="你在盾墙后开口。墙往前挪了半步，像被歌推着走。",
         use_fx={"cha": 1, "str": 1, "con": 1}, use_cd="war"),
    dict(flag="skill_lullaby", gold=1, jobs=("bard", "cleric", "druid"),
         get="安眠曲先把自己唱困。你学会在困之前把最后一句送给别人。",
         get_fx={"gold": -1, "cha": 1, "wis": 1},
         lose="曲子被酒馆唱滥。它不再催眠，只催酒。",
         lose_fx={"cha": -1, "wis": 1},
         use="守夜人听完副歌就倒了。你从他的梦旁边走过，没有踩到。",
         use_fx={"cha": 1, "agi": 1}, use_cd="social"),
    dict(flag="skill_satire", gold=1, jobs=("bard", "rogue"),
         get="嘲讽诗要把刀藏在笑里。你写第一首时，自己先被划了一下。",
         get_fx={"gold": -1, "cha": 1, "int": 1},
         lose="有人比你更会骂。你的诗变成开场，别人的才是主菜。",
         lose_fx={"cha": -1, "wis": 1},
         use="你当众把领主的纹章读成洗衣账单。人群笑完，领主的手松开了剑。",
         use_fx={"cha": 2, "int": 1}, use_cd="social"),
    dict(flag="skill_memory_ballad", gold=1, jobs=("bard", "wizard", "cleric"),
         get="记忆谣能把别人忘掉的一天唱回来。你试唱自己的童年，唱到一半停了。",
         get_fx={"gold": -1, "int": 1, "cha": 1},
         lose="你开始记混别人的日子。谣还在，主线不清。",
         lose_fx={"int": -1, "wis": 1},
         use="证人忘掉的细节被你唱出来。法庭第一次感谢艺术。",
         use_fx={"int": 1, "cha": 1, "wis": 1}, use_cd="court"),
    dict(flag="skill_countercharm", gold=1, jobs=("bard", "cleric", "wizard"),
         get="破咒谐是一串不和谐。你把它练到刚好能把别人的和谐拆开。",
         get_fx={"gold": -1, "cha": 1, "int": 1},
         lose="你的谐变成走调。走调能扫兴，不能破咒。",
         lose_fx={"cha": -1, "int": 1},
         use="魅惑从同伴眼里退回去，像退潮。同伴骂了你一句，声音是自己的。",
         use_fx={"cha": 1, "wis": 1}, use_cd="magic"),
    dict(flag="skill_iron_bone", gold=0, jobs=("monk", "barbarian", "fighter"),
         get="铁骨从挨打开始。你挨到第三次还能站，木人开始尊敬你。",
         get_fx={"con": 1, "str": 1},
         lose="一次内伤让你重新变脆。脆不是错，只是不再自称铁。",
         lose_fx={"con": -1, "wis": 1},
         use="锤打在你肋上，锤先痛。你还在，锤的主人开始计算自己的寿命。",
         use_fx={"con": 2}, use_cd="combat"),
    dict(flag="skill_hold_breath", gold=0, jobs=("monk", "rogue", "ranger", "druid"),
         get="屏息数到一百时世界变窄。你学会在窄里把事做完。",
         get_fx={"con": 1, "agi": 1},
         lose="烟把你的肺教坏了。一百变成二十，二十变成咳嗽。",
         lose_fx={"con": -1, "wis": 1},
         use="你从水下走过闸门。闸门上的人还在等气泡，气泡没有你。",
         use_fx={"con": 1, "agi": 1}, use_cd="sea"),
    dict(flag="skill_bell_body", gold=0, jobs=("monk",),
         get="金钟把身体当成一口缸。敲响时你不碎，碎的是来敲的东西。",
         get_fx={"con": 1, "wis": 1},
         lose="你在一次醉后把缸打开了。风灌进去，金钟变成普通的肚子。",
         lose_fx={"con": -1, "cha": 1},
         use="拳打在你身上，回音打在对方手腕上。双方都听到了道理。",
         use_fx={"con": 1, "str": 1}, use_cd="combat"),
    dict(flag="skill_light_step", gold=0, jobs=("monk", "rogue", "ranger"),
         get="轻身让屋顶把你当成猫。猫不收房租。",
         get_fx={"agi": 1, "wis": 1},
         lose="你胖了一寸。屋顶开始按人收费。",
         lose_fx={"agi": -1, "con": 1},
         use="你从屋脊抄近路。瓦只碎了一块，碎给月亮看。",
         use_fx={"agi": 1, "con": 1}, use_cd="crime"),
    dict(flag="skill_cold_resist", gold=0, jobs=("monk", "barbarian", "ranger", "druid"),
         get="耐寒从把雪含在嘴里开始。你含到舌头同意：冷也可以是一种衣服。",
         get_fx={"con": 1},
         lose="一次高烧把这份衣服脱了。雪重新刺人。",
         lose_fx={"con": -1, "wis": 1},
         use="暴风雪里你还在走路。同行的人开始怀疑你是不是还需要火。",
         use_fx={"con": 1, "str": 1}, use_cd="wilderness"),
    dict(flag="skill_lip_read", gold=1, jobs=("rogue", "bard", "wizard", "monk"),
         get="读唇在禁声的书斋里学会。先生的口型比板书诚实。",
         get_fx={"gold": -1, "int": 1, "wis": 1},
         lose="你开始看错。口型变成你想看到的话。这比聋更危险。",
         lose_fx={"int": -1, "wis": 1},
         use="隔着玻璃你读完一场交易。玻璃没有签名，你已经知道价钱。",
         use_fx={"int": 1, "gold": 2}, use_cd="court"),
    dict(flag="skill_detect_lie", gold=1, jobs=("paladin", "cleric", "rogue", "bard"),
         get="测谎先测自己。你对自己说了三次‘没事’，第三次时手出汗。你学会了。",
         get_fx={"gold": -1, "wis": 1, "cha": 1},
         lose="你开始对所有人出汗。测谎变成一种不礼貌的体质。",
         lose_fx={"cha": -1, "wis": 1},
         use="商人说货物从未沾血。你看着他的眼白，把价钱砍掉三分之一。",
         use_fx={"wis": 1, "gold": 2}, use_cd="social"),
    dict(flag="skill_steady", gold=0, jobs=("monk", "cleric", "paladin", "fighter"),
         get="镇定是把心跳从鼓改成钟。你在箭雨里把钟走完一轮。",
         get_fx={"wis": 1, "con": 1},
         lose="一次惊吓把钟砸了。鼓又回来，鼓没有节奏。",
         lose_fx={"wis": -1, "con": 1},
         use="恐慌在队伍里传染。你先把呼吸放慢，传染因此少了一半。",
         use_fx={"wis": 1, "cha": 1, "con": 1}, use_cd="war"),
    dict(flag="skill_dream_recall", gold=1, jobs=("wizard", "warlock", "druid", "bard"),
         get="梦忆让你把夜里的句子抄下来。有些句子属于别人，有些属于明天。",
         get_fx={"gold": -1, "int": 1, "wis": 1},
         lose="你抄到分不清醒和睡。白天开始收使用费。",
         lose_fx={"wis": -1, "con": -1, "int": 1},
         use="你在梦里看见井盖上的字。醒来后你按那行字挖，挖到一把不属于这个世纪的钥匙。",
         use_fx={"int": 1, "wis": 1, "gold": 1}, use_cd="weird"),
    dict(flag="skill_mind_ward", gold=2, jobs=("wizard", "warlock", "monk", "cleric"),
         get="拒心魔是一扇只对内开的门。你把门练到能在被人推的时候反推一下。",
         get_fx={"gold": -2, "int": 1, "wis": 1},
         lose="门轴锈了。低语重新变成客人。",
         lose_fx={"int": -1, "wis": 1},
         use="夺心魔的句子进到一半被弹回去。它第一次用自己的声音骂了一句。",
         use_fx={"int": 1, "wis": 1, "con": 1}, use_cd="weird"),
    dict(flag="skill_enchant_weapon", gold=2, jobs=("wizard", "cleric"), or_flags=[{"origin": "artisan"}],
         get="附魔武器要先让武器同意发光。你的剑同意了一晚，一晚够用。",
         get_fx={"gold": -2, "int": 1},
         lose="你把符文写反。剑亮了一下，然后只亮锈。",
         lose_fx={"int": -1, "str": 1},
         use="你给同伴的刀刻上一小时的锋。一小时后刀还是刀，敌人已经不是敌人。",
         use_fx={"int": 1, "str": 1, "cha": 1}, use_cd="craft"),
    dict(flag="skill_alchemy", gold=2, jobs=("wizard", "rogue", "cleric"),
         get="炼金入门是把失败分类。你会了三种不会炸的配方，和一种会炸但有用的。",
         get_fx={"gold": -2, "int": 1},
         lose="一次爆炸让你改用现成的药。现成的药不认你做同行。",
         lose_fx={"int": -1, "con": 1},
         use="你把两瓶失败兑成一瓶成功。成功味道像悔过，作用像门闩。",
         use_fx={"int": 1, "con": 1, "gold": 1}, use_cd="craft"),
    dict(flag="skill_temper", gold=1, or_flags=[{"origin": "artisan"}, {"job": "fighter"}],
         get="锻造回火看颜色，不看钟。你看出第三次橙，铁才肯硬。",
         get_fx={"gold": -1, "str": 1, "int": 1},
         lose="你的眼被烟熏花。颜色混成一种，铁也混成一种。",
         lose_fx={"int": -1, "con": 1},
         use="你把卷刃敲直并回火。第二天这柄刀替你挡了一箭，像还人情。",
         use_fx={"str": 1, "con": 1}, use_cd="craft"),
    dict(flag="skill_survey", gold=1, jobs=("ranger", "wizard", "rogue"), or_flags=[{"origin": "artisan"}],
         get="测绘让空白变成可走的谎。你量过的路少吃人。",
         get_fx={"gold": -1, "int": 1, "wis": 1},
         lose="你把比例尺记反。地图把人带去悬崖，悬崖很真实。",
         lose_fx={"int": -1, "wis": 1},
         use="你画出一条商队不敢走的近路。近路收了钱，也收了两声谢谢。",
         use_fx={"int": 1, "gold": 3}, use_cd="craft"),
    dict(flag="skill_cook_magic", gold=1, jobs=("bard", "druid", "cleric"), or_flags=[{"origin": "farmer"}],
         get="烹饪奇术是把火候写成咒。你的汤能让人多走十里，也能让人说实话。",
         get_fx={"gold": -1, "cha": 1, "wis": 1},
         lose="你把盐当成硫磺。汤很真诚，真诚得没人喝。",
         lose_fx={"cha": -1, "con": 1},
         use="你做了一锅能压惊的粥。队伍把粥喝完，把逃的念头也喝完。",
         use_fx={"cha": 1, "con": 1}, use_cd="social"),
    dict(flag="skill_blood_rite", gold=0, jobs=("warlock", "cleric", "wizard"),
         get="血祭只要一滴，多了是浪费，少了是欺骗。你学会了刚好。",
         get_fx={"int": 1, "wis": -1, "con": 1},
         lose="你在一次恶心之后把仪式吐掉了。吐掉的东西不再回来。",
         lose_fx={"wis": 1, "con": 1, "cha": 1},
         use="你滴血在门上。门开了，里面的东西先问你还剩几滴。",
         use_fx={"int": 1, "cha": 1, "con": -1}, use_cd="weird"),
    dict(flag="skill_dead_whisper", gold=0, jobs=("warlock", "cleric", "wizard", "bard"),
         get="亡灵低语像把耳朵伸进井。井回你半句话，半句已够用。",
         get_fx={"wis": 1, "int": 1, "cha": -1},
         lose="井不再回。你的耳朵里只剩自己的血声。",
         lose_fx={"cha": 1, "wis": 1},
         use="你问死者钥匙在哪。死者说在他最恨的那只靴子里。靴子还在。",
         use_fx={"int": 1, "wis": 1, "gold": 2}, use_cd="undead"),
    dict(flag="skill_raise_pact", gold=0, jobs=("warlock",),
         get="契约加码是跟梦里的东西重新谈判。它加了你的寿命，你加了它的名字。",
         get_fx={"cha": 1, "int": 1, "con": -1},
         lose="名字被它收回。加码变成原价，原价仍不便宜。",
         lose_fx={"cha": -1, "wis": 1, "con": 1},
         use="你把契约摊开再签一行。火焰按新的条款替你挡了一次。条款会记仇。",
         use_fx={"cha": 1, "int": 1, "con": -1}, use_cd="weird"),
    dict(flag="skill_fate_thread", gold=0, jobs=("warlock", "cleric", "wizard", "sorcerer"),
         get="改命一线只能拉一次，拉歪了是别人的命。你练习在线上打结，不练习剪。",
         get_fx={"wis": 1, "int": 1},
         lose="线从你视野里消失。命运恢复无人值守。",
         lose_fx={"wis": -1, "con": 1},
         use="箭要来时你轻轻一扯。箭改去钉帽子。帽子死了，人还在。",
         use_fx={"agi": 1, "wis": 1, "cha": 1}, use_cd="weird"),
    dict(flag="skill_feign_death", gold=0, jobs=("rogue", "monk", "warlock", "bard"),
         get="假死要先把心跳藏好。你藏到验尸的人开始写报告，才把报告作废。",
         get_fx={"con": 1, "int": 1, "cha": 1},
         lose="你在一次真正的休克后不敢再装。装和真的边界被你自己怕了。",
         lose_fx={"con": -1, "wis": 1},
         use="绞索套上时你先走了。他们把你抬去埋，埋到一半你咳嗽。报告改写。",
         use_fx={"con": 1, "agi": 1, "cha": 1}, use_cd="crime"),
]
